sever:
  port: 8080

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/eelex?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhoujielun133
    driver-class-name: com.mysql.cj.jdbc.Driver
