server:
   port: 8085


spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/eelex
    username: root
    password: zhoujielun133
    driver-class-name: com.mysql.cj.jdbc.Driver
    useSSL: false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
   map-underscore-to-camel-case: false

servlet:
  context-path: /usercenterbackend

